services:
  app:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules  # Prevents overriding installed dependencies
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
